name: Send Daily Motivation SMS

on:
  schedule:
    # Runs at 7:00 AM UTC every day
    - cron: '0 7 * * *'
  workflow_dispatch: # manual trigger

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run motivational SMS script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_SMS_NUMBER: ${{ secrets.FROM_NUMBER }}
          MY_PHONE_NUMBER: ${{ secrets.TO_NUMBER }}
        run: npm run start
